pull_request_rules:
  - name: Automerge to main
    conditions:
      - base=main
      - label=S:automerge
    actions:
      merge:
        method: squash
        strict: true
        commit_message: title+body
