project_name: ostracon

env:
  # Require use of Go modules.
  - GO111MODULE=on

builds:
  - id: "Ostracon"
    main: ./cmd/ostracon/main.go
    ldflags:
      - -s -w -X github.com/line/ostracon/version.OCCoreSemVer={{ .Version }}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

checksum:
  name_template: SHA256SUMS-{{.Version}}.txt
  algorithm: sha256

release:
  name_template: "{{.Version}} (WARNING: BETA SOFTWARE)"
