codecov:
  token: a0d06f00-e140-4525-93f9-1722b2c9d5d2

coverage:
  precision: 2
  round: down
  range: "70...100"
  github_checks:
    annotations: false

  status:
    project:
      default:
        threshold: 1%
    patch: on
    changes: off

comment:
layout: "diff, files"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes

ignore:
  - "docs"
  - "DOCKER"
  - "scripts"
  - "libs/pubsub/query/query.peg.go"
