name: Lint
# Lint runs golangci-lint over the entire Ostracon repository
# This workflow is run on every pull request and push to master
# The `golangci` job will pass without running if no *.{go, mod, sum} files have been modified.
on:
  pull_request:
  push:
jobs:
  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    timeout-minutes: 4
    steps:
      - uses: actions/checkout@v2
      - uses: technote-space/get-diff-action@v5.0.1
        with:
          PATTERNS: |
            **/**.go
            go.mod
            go.sum
      - uses: golangci/golangci-lint-action@v2.2.1
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.31
          args: --timeout 10m --skip-files "_test\.go" # for skip unused linter (https://github.com/golangci/golangci-lint/issues/791)
          github-token: ${{ secrets.github_token }}
        if: env.GIT_DIFF
