name: Build & Push OC Proto Builder
on:
  pull_request:
    paths:
      - "tools/proto/*"
  push:
    branches:
      - main
    paths:
      - "tools/proto/*"
  schedule:
    # run this job once a month to recieve any go or buf updates
    - cron: "* * 1 * *"

jobs:
  build-proto:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Prepare
        id: prep
        run: |
          DOCKER_IMAGE=ostracondev/docker-build-proto
          VERSION=noop
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          elif [[ $GITHUB_REF == refs/heads/* ]]; then
            VERSION=$(echo ${GITHUB_REF#refs/heads/} | sed -r 's#/+#-#g')
            DEFAULT_BRANCH=$(curl -s -H "Accept: application/vnd.github.v3+json" \
                             https://api.github.com/repos/line/ostracon | \
                             grep default_branch | \
                             cut -d"\"" -f4)
            if [ "$DEFAULT_BRANCH" = "$VERSION" ]; then
              VERSION=latest
            fi
          fi
          TAGS="${DOCKER_IMAGE}:${VERSION}"
          if [[ $VERSION =~ ^v[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
            TAGS="$TAGS,${DOCKER_IMAGE}:${VERSION%.*}"
          fi
          echo ::set-output name=tags::${TAGS}

#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v1.3.0

#      - name: Login to DockerHub
#        uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}

#      - name: Publish to Docker Hub
#        uses: docker/build-push-action@v2.4.0
#        with:
#          context: ./tools/proto
#          file: ./tools/proto/Dockerfile
#          push: ${{ github.event_name != 'pull_request' }}
#          tags: ${{ steps.prep.outputs.tags }}
